//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCKutuphane.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbKutuphaneEntities : DbContext
    {
        public DbKutuphaneEntities()
            : base("name=DbKutuphaneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLCezalar> TBLCezalar { get; set; }
        public virtual DbSet<TBLHareket> TBLHareket { get; set; }
        public virtual DbSet<TBLKasaa> TBLKasaa { get; set; }
        public virtual DbSet<TBLKategori> TBLKategori { get; set; }
        public virtual DbSet<TBLKitap> TBLKitap { get; set; }
        public virtual DbSet<TBLUyeler> TBLUyeler { get; set; }
        public virtual DbSet<TBLYazar> TBLYazar { get; set; }
        public virtual DbSet<TBLPersonel> TBLPersonel { get; set; }
        public virtual DbSet<TBLHakkımızda> TBLHakkımızda { get; set; }
        public virtual DbSet<TBLİletişim> TBLİletişim { get; set; }
        public virtual DbSet<TBLMesajlar> TBLMesajlar { get; set; }
    
        public virtual ObjectResult<string> EnFazlaKitapYazar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("EnFazlaKitapYazar");
        }
    
        public virtual ObjectResult<string> EnfazlaÜye()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("EnfazlaÜye");
        }
    
        public virtual ObjectResult<string> EnfazlaÜyee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("EnfazlaÜyee");
        }
    }
}
