//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLUyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLUyeler()
        {
            this.TBLCezalar = new HashSet<TBLCezalar>();
            this.TBLHareket = new HashSet<TBLHareket>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage ="Adı Boş Bırakamazsınız")]
        [StringLength(20,ErrorMessage = "En Fazla 20 Karakter Girebilirsiniz")]
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string MAİL { get; set; }
        public string KULLANICIADI { get; set; }
       
        [StringLength(10, ErrorMessage = "En Fazla 10 Karakter Girebilirsiniz")]
        public string SIFRE { get; set; }
        public string FOTOGRAF { get; set; }
        public string TELEFON { get; set; }
        public string OKUL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCezalar> TBLCezalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHareket> TBLHareket { get; set; }
    }
}
